version: '3.4'

services:  
  sqlserverex:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    ports: 
      - 1433:1433
    environment:
       ACCEPT_EULA: Y
       SA_PASSWORD: Test@12345678
       MSSQL_PID: Express
  answerproject:
    image: ${DOCKER_REGISTRY-}answerproject
    depends_on:
      - sqlserverex
    build:
      context: .
      dockerfile: AnswerProject/Dockerfile
    ports:
      - 8080:80