// <auto-generated />
using System;
using AnswerProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnswerProject.Migrations
{
    [DbContext(typeof(AnswerContext))]
    partial class AnswerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AnswerProject.Models.Answer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ADate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("AnswerProject.Models.AnswerItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Answer_Id")
                        .HasColumnType("bigint");

                    b.Property<long>("Question_Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Answer_Id");

                    b.HasIndex("Question_Id");

                    b.ToTable("AnswerItems");
                });

            modelBuilder.Entity("AnswerProject.Models.Question", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DataType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Enumeration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DataType = "string",
                            Text = "Введите имя"
                        },
                        new
                        {
                            Id = 2L,
                            DataType = "number",
                            Text = "Введите возраст"
                        },
                        new
                        {
                            Id = 3L,
                            DataType = "enum",
                            Enumeration = "муж;жен;неопр",
                            Text = "Введите пол"
                        },
                        new
                        {
                            Id = 4L,
                            DataType = "date",
                            Text = "Введите дату рождения"
                        },
                        new
                        {
                            Id = 5L,
                            DataType = "enum",
                            Enumeration = "холост/не замужем;женат/замужем;разведен/а",
                            Text = "Введите семейное положение"
                        },
                        new
                        {
                            Id = 6L,
                            DataType = "bool",
                            Text = "Любите ли вы программировать"
                        });
                });

            modelBuilder.Entity("AnswerProject.Models.AnswerItem", b =>
                {
                    b.HasOne("AnswerProject.Models.Answer", "Answer")
                        .WithMany("AnswerItems")
                        .HasForeignKey("Answer_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnswerProject.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("Question_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
